### ISSUE TITLE
Status & Plan

### ISSUE THREAD

**Issue by WiestDaessle** [OpenCleanEnergy/OpenMI#1]
Hello guy's,

Searching for an open source Micro Inverter i found your starting project, being a software side guy, i wondered how/if i can give some help on this side of the project. Also i'm mainly involved in datascience and deeplearning, i also wonder how/if this could be used in such a process specifically in the MPTT side or some computational step.

How to get in touch and start discussion on this project .

Best regards

**Comment by just-seba** [comment]
Thank you very much for reaching out.

As this project is still at a fairly early stage of development, we are unable to accept any contributions right now. As soon as the project is more stable we will accept contributions.

We will add an **contribution guideline** and a **roadmap** with all the information you need soon.
Please star and keep checking this repositoy for updates. We will be in touch as soon as we accept contributions.

Best regards.

**Comment by just-seba** [comment]
See [CONTRIBUTING.md](https://github.com/OpenCleanEnergy/OpenMI/blob/main/CONTRIBUTING.md)
